---
- name: List AMI backups
  hosts: local
  connection: local

  vars:
   region: ap-southeast-2
   name_ami: "*"
   owner_ami: self

  tasks:

   - name: List backups
     ec2_ami_find:
       region: "{{ region }}"
       name: "{{ name_ami }}"
       owner: "{{ owner_ami }}"
     register: ami_find

   - name: List AMI images
     debug:
       msg: "{{ ami_find | json_query('results[].name') }}"
